"""Licence verification. Offline, dependency-free, and unable to sign.

Three constraints shaped this, and each one ruled something out.

It must work with no network. A licence check that phones home would break the
promise the product is sold on, and the airgap test would fail the build, which
is the correct outcome. So verification is a signature check against a public
key compiled into this file, and nothing here opens a socket.

It must add no dependency. The wheel has zero runtime dependencies and that is
a selling point rather than an accident, so this carries the Ed25519
verification arithmetic itself. It is the reference formulation from RFC 8032,
which is slow and obviously correct rather than fast and clever. Speed is
irrelevant: one signature is checked when a licence is loaded, once.

It must not be able to issue a licence. There is no signing code in the server,
by design. Signing lives in scripts/sign_licence.py and needs a private key that
never ships. Someone reading every line of the product still cannot mint a
licence for it.

WHAT THIS IS NOT: copy protection. The core is MIT, so anyone may delete this
file and carry on, and that is a legitimate use of the licence they were given.
This exists for the organisation whose procurement requires a paid licence for
production use and whose auditors ask to see it. It is an instrument of honesty
between adults, not a lock, and treating it as a lock would mean adding the
telemetry we refuse to add.

Copyright 2026 Michael Brandon Clifford. MIT licensed.
"""
from __future__ import annotations

import base64
import binascii
import hashlib
import json
import os
import time

# ── Ed25519 verification (RFC 8032, reference formulation) ───────────────────
_P = 2 ** 255 - 19
_L = 2 ** 252 + 27742317777372353535851937790883648493
_D = -121665 * pow(121666, _P - 2, _P) % _P
_I = pow(2, (_P - 1) // 4, _P)


def _xrecover(y: int) -> int:
    xx = (y * y - 1) * pow(_D * y * y + 1, _P - 2, _P)
    x = pow(xx, (_P + 3) // 8, _P)
    if (x * x - xx) % _P != 0:
        x = (x * _I) % _P
    if x % 2 != 0:
        x = _P - x
    return x


_BY = 4 * pow(5, _P - 2, _P) % _P
_B = (_xrecover(_BY) % _P, _BY)


def _edwards(a, b):
    x1, y1 = a
    x2, y2 = b
    k = _D * x1 * x2 * y1 * y2
    x3 = (x1 * y2 + x2 * y1) * pow(1 + k, _P - 2, _P)
    y3 = (y1 * y2 + x1 * x2) * pow(1 - k, _P - 2, _P)
    return (x3 % _P, y3 % _P)


def _scalarmult(pt, e):
    if e == 0:
        return (0, 1)
    q = _scalarmult(pt, e // 2)
    q = _edwards(q, q)
    return _edwards(q, pt) if e & 1 else q


def _decodeint(s: bytes) -> int:
    return int.from_bytes(s, "little")


def _decodepoint(s: bytes):
    y = int.from_bytes(s, "little") & ((1 << 255) - 1)
    x = _xrecover(y)
    if x & 1 != (s[31] >> 7) & 1:
        x = _P - x
    pt = (x, y)
    if (-pt[0] * pt[0] + pt[1] * pt[1] - 1 - _D * pt[0] * pt[0] * pt[1] * pt[1]) % _P != 0:
        raise ValueError("point is not on the curve")
    return pt


def _encodepoint(pt) -> bytes:
    x, y = pt
    return (y | ((x & 1) << 255)).to_bytes(32, "little")


def ed25519_verify(public_key: bytes, message: bytes, signature: bytes) -> bool:
    """True when `signature` is a valid Ed25519 signature over `message`.

    Every failure path returns False rather than raising, because a malformed
    licence and an unsigned one mean the same thing to the caller: not
    licensed."""
    try:
        if len(signature) != 64 or len(public_key) != 32:
            return False
        r = _decodepoint(signature[:32])
        a = _decodepoint(public_key)
        s = _decodeint(signature[32:])
        if s >= _L:
            return False
        h = _decodeint(hashlib.sha512(
            signature[:32] + public_key + message).digest()) % _L
        return _encodepoint(_scalarmult(_B, s)) == _encodepoint(
            _edwards(r, _scalarmult(a, h)))
    except Exception:
        return False


# ── the licence itself ───────────────────────────────────────────────────────
# The public half of the licence-signing key. The private half is not in this
# repository and never will be.
#
# This is the real issuer key, and being public is the whole point of it: it
# can verify a licence and cannot produce one.
#
# It shipped EMPTY until an issuer key existed, because the first draft carried
# a plausible-looking hex string as a placeholder which turned out to be the
# public key for the all-zero seed. Anyone could have minted themselves a
# licence with thirty-two zero bytes. A build that trusts a key nobody chose is
# worse than one that trusts none, so if this is ever cleared, clear it to "".
#
# The matching private half was generated by scripts/sign_licence.py --keygen,
# lives in a 0600 file outside this repository, and has never been printed to a
# terminal. Replacing it means reissuing every licence, so it is worth keeping.
ISSUER_PUBLIC_KEY = os.environ.get(
    "OMEM_LICENCE_PUBKEY",
    "73ca370ec65d6fbe0de9dbe6a04dbf0bdc7310b102853b156a66e695a8cc36c4").strip()

FEATURES = {
    # Named here rather than invented at each call site, so that what a licence
    # can unlock is a short readable list rather than a scatter of strings.
    "approval_policy": "Policy over who may approve which risk class",
    "auditor_export": "Signed conformance bundle for an external auditor",
    "retention_hold": "Legal hold that survives the retention sweep",
    "multi_project": "Governance across projects from one place",
}


class Licence:
    """A verified licence. Constructing one does not verify it; `load` does."""

    def __init__(self, claims: dict):
        self.customer = str(claims.get("customer") or "unknown")
        self.issued = float(claims.get("issued") or 0)
        self.expires = float(claims.get("expires") or 0)
        self.features = tuple(claims.get("features") or ())
        self.note = str(claims.get("note") or "")

    @property
    def expired(self) -> bool:
        return bool(self.expires) and time.time() > self.expires

    def has(self, feature: str) -> bool:
        """An expired licence unlocks nothing. It does not disable the product,
        which would turn a billing lapse into an outage, and an outage into a
        reason never to buy infrastructure from a one-person company."""
        return not self.expired and feature in self.features

    def as_dict(self) -> dict:
        return {"customer": self.customer, "issued": self.issued,
                "expires": self.expires, "features": list(self.features),
                "expired": self.expired, "note": self.note}


def parse(token: str) -> tuple:
    """(Licence, None) when the token verifies, (None, reason) when it does not.

    A token is `<base64url claims>.<base64url signature>`, which is short enough
    to paste into an environment variable and readable enough that a customer
    can see exactly what they were sold without running anything."""
    if not ISSUER_PUBLIC_KEY:
        return None, "no issuer key is configured, so no licence can verify"
    if not token or "." not in token:
        return None, "not a licence token"
    body, _, sig = token.strip().partition(".")
    try:
        pad = "=" * (-len(body) % 4)
        claims_raw = base64.urlsafe_b64decode(body + pad)
        pad = "=" * (-len(sig) % 4)
        signature = base64.urlsafe_b64decode(sig + pad)
        pubkey = binascii.unhexlify(ISSUER_PUBLIC_KEY)
    except Exception:
        return None, "malformed licence token"
    if not ed25519_verify(pubkey, claims_raw, signature):
        return None, "signature does not verify against the issuer key"
    try:
        claims = json.loads(claims_raw.decode("utf-8"))
    except Exception:
        return None, "licence payload is not readable"
    if not isinstance(claims, dict):
        return None, "licence payload is not an object"
    lic = Licence(claims)
    if lic.expired:
        return lic, "licence expired"
    return lic, None


def load() -> tuple:
    """The active licence, from OMEM_LICENCE or the file OMEM_LICENCE_FILE
    points at. Returns (None, None) when there is no licence at all, which is
    the ordinary case and not an error: everything in the MIT core works
    without one."""
    token = os.environ.get("OMEM_LICENCE", "").strip()
    if not token:
        path = os.environ.get("OMEM_LICENCE_FILE", "").strip()
        if path and os.path.exists(path):
            try:
                with open(path, encoding="utf-8") as f:
                    token = f.read().strip()
            except Exception:
                return None, "licence file could not be read"
    if not token:
        return None, None
    return parse(token)


def status() -> dict:
    """What to show a human or an auditor asking whether this install is
    licensed, safe to serve without authentication beyond the usual read
    permission: it names no secret and asserts nothing about the customer's
    data."""
    lic, reason = load()
    if lic is None and reason is None:
        return {"licensed": False, "reason": "no licence configured",
                "features": [], "catalogue": FEATURES}
    if lic is None:
        return {"licensed": False, "reason": reason, "features": [],
                "catalogue": FEATURES}
    d = lic.as_dict()
    d.update({"licensed": not lic.expired,
              "reason": reason or None,
              "features": [f for f in lic.features if lic.has(f)],
              "catalogue": FEATURES})
    return d


def has(feature: str) -> bool:
    """The one call sites use. Cheap enough to call per request, and it fails
    closed: any problem at all means the feature is off."""
    lic, _ = load()
    return bool(lic and lic.has(feature))
